version: '3'

services:

  mongodb:
    hostname: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${ME_CONFIG_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${ME_CONFIG_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: on-failure:5
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s