version: '3'

services:

  cache:
    hostname: redis
    image: redis:7.4-alpine
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes: 
      - redis_data:/data
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

